CGPA_MENU_CHOICE = 1
CGPA_PREV_CREDITS = 2
CGPA_PREV_CGPA = 3
CGPA_COURSE_COUNT = 4
CGPA_COURSE_CREDIT = 5
CGPA_COURSE_GRADE = 6

FEE_ACADEMIC_SYSTEM = 10
FEE_CREDIT_FEE = 11
FEE_TRIMESTER_FEE = 12
FEE_REG_CREDITS = 13
FEE_RETAKE_COUNT = 14
FEE_RETAKE_CREDITS = 15
FEE_DISCOUNT_TYPE = 16
FEE_DISCOUNT_PERCENT = 17

ADMIN_BROADCAST = 20
ADMIN_BROADCAST_MESSAGE = 21

SCHOLARSHIP_GPA = 500
SCHOLARSHIP_PROGRAM = 501
SCHOLARSHIP_SIZE = 502
SCHOLARSHIP_CREDITS = 503
SCHOLARSHIP_HIGHER_CHOICE = 504
SCHOLARSHIP_HIGHER_COUNT = 505
