(
    CGPA_MENU_CHOICE,
    CGPA_PREV_CREDITS,
    CGPA_PREV_CGPA,
    CGPA_COURSE_COUNT,
    CGPA_COURSE_CREDIT,
    CGPA_COURSE_GRADE,
) = range(6)


(
    FEE_REG_CREDITS,
    FEE_RETAKE_COUNT,
    FEE_RETAKE_CREDITS,
    FEE_DISCOUNT_TYPE,
    FEE_DISCOUNT_PERCENT,
) = range(10, 15)


(
    ADMIN_MENU,
    ADMIN_SETTING_EDIT,
    ADMIN_BROADCAST_MESSAGE,
) = range(20, 23)
