CGPA_MENU_CHOICE = 1
CGPA_PREV_CREDITS = 2
CGPA_PREV_CGPA = 3
CGPA_COURSE_COUNT = 4
CGPA_COURSE_CREDIT = 5
CGPA_COURSE_GRADE = 6

FEE_CREDIT_FEE = 10
FEE_TRIMESTER_FEE = 11
FEE_REG_CREDITS = 12
FEE_RETAKE_COUNT = 13
FEE_RETAKE_CREDITS = 14
FEE_DISCOUNT_TYPE = 15
FEE_DISCOUNT_PERCENT = 16

ADMIN_MENU = 20
ADMIN_SETTING_EDIT = 21
ADMIN_BROADCAST_MESSAGE = 22
